# Generated by Django 5.0.4 on 2024-05-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_licence_number_alter_manufacturer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('license_number',)},
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='licence_number',
            new_name='license_number',
        ),
    ]
